### ISSUE TITLE
Update peer dependency/support for Gatsby v4

### ISSUE THREAD

**Issue by michaelck** [larowlan/gatsby-source-drupal-menu-links#24]
I'm testing a [migration from Gatsby v3 to v4](https://v4.gatsbyjs.com/docs/reference/release-notes/migrating-from-v3-to-v4/#changes-to-built-in-types) and noticed the following warning while building a development site:

```warn Plugin gatsby-source-drupal-menu-links is not compatible with your gatsby version 4.1.2 - It requires gatsby@^3.0.0```

I figured I'd open an issue in the event that it wasn't on your radar.

Thanks for your work on this handy plugin.

**Comment by larowlan** [comment]
Thanks, I'm noting using v4 anywhere yet, but would happily merge a PR

**Comment by michaelck** [comment]
Thanks, @larowlan. I've opened a PR at #25. I welcome any thoughts or feedback.
