### ISSUE TITLE
support for Gatsby v5

### ISSUE THREAD

**Issue by anandtoshniwal** [larowlan/gatsby-source-drupal-menu-links#36]
While using gatsby 5 getting below warning in development and build mode, seems like modification requires in peerDependency.
 
` Plugin gatsby-source-drupal-menu-links is not compatible with your gatsby version 5.5.0 - It requires gatsby@^3.0.0 || ^4.0.0`

Thanks for your work on this handy plugin.

**Comment by TwisterMc** [comment]
I agree, this should be updated. I don't think anything is broken, so is it just a dependency update?

**Comment by larowlan** [comment]
I'd welcome pull requests here, not using v5 yet personally

**Comment by cienvaras** [comment]
Created #37 to fix this. The plugin works really well in Gatsby 5, just needed the peer dependencies update. Also updated the outdated dependencies.

Let me know if there's something to fix!

**Comment by ccesare** [comment]
Any chance we could get a new release that includes this update?
