### ISSUE TITLE
Update to gatsby version 3.0

### ISSUE THREAD

**Issue by snschau** [larowlan/gatsby-source-drupal-menu-links#8]
I upgraded to Gatsby Version 3.0.0 and when I do a gatsby develop or build - I get the following warning:

Plugin gatsby-source-drupal-menu-links is not compatible with your gatsby version 3.0.0 - It requires gatsby@^2.0.15

**Comment by larowlan** [comment]
Gatsby 3 has been out 2 days, we haven't updated the plugin yet.

Looking at the migration docs I think we won't have much to do

**Comment by larowlan** [comment]
Gatsby 3 has been out 2 days, we haven't updated the plugin yet.

Looking at the migration docs I think we won't have much to do
